name: ensemble_learning
channels:
dependencies:
  - python=3.10
  - pip=22.2.2
  - numpy=1.23.4
  - pip:
    - scipy==1.9.2 
    - pandas==1.5.0
    - scikit-learn==1.2
    - matplotlib==3.6.1
    - seaborn==0.12.0 
    - lightGBM==3.3.3
    - xgboost==1.6.2 
    - catboost==1.1 
    - interpret
    - category_encoders
    - dirty_cat==0.3.0
    - jupyterlab
